language: go

go:
  - 1.8.x

before_install:
  - go get github.com/mattn/goveralls

script:
  - mkdir -p private
  - echo $SERVICE_ACCOUNT > private/service_account.json
  - $HOME/gopath/bin/goveralls -service=travis-ci
